[filter]
name : bw01
type : bw
dim : 2
cf : 1

[filter]
name : none01
type : none

[sensor]
name : lfsensor
type : 6ft
frame : {
 1.0 0.0 0.0 0.0
 0.0 1.0 0.0 0.0
 0.0 0.0 1.0 0.001
}
filter :
 bw01 bw01 bw01
 bw01 bw01 bw01
link : left_foot

[sensor]
name : rfsensor
type : 6ft
frame : {
 1.0 0.0 0.0 0.0
 0.0 1.0 0.0 0.0
 0.0 0.0 1.0 0.001
}
filter :
 bw01 bw01 bw01
 bw01 bw01 bw01
link : right_foot

[estimator]
type : zmp
leftfoot :  lfsensor
rightfoot : rfsensor
