[joint]
waist_base   0.001 0 0 0 0 0 0
waist_p      0 0
waist_r	     0 0
neck_p       0 0
lhip_y	     0.001 0
lhip_p	     0.001 0
lhip_r	     0.001 0
lknee_p	     0.001 0
lankle_r     0.001 0
lankle_p     0.001 0
rhip_y	     0.001 0
rhip_p	     0.001 0
rhip_r	     0.001 0
rknee_p	     0.001 0
rankle_r     0.001 0
rankle_p     0.001 0
lscaplae_y   0 0
lshoulder_p  0 0
lshoulder_r  0 15
lshoulder_y  0 -90
lelbow_p     0 -15
lwrist_y     0 0
lwrist_r     0 -15
lwrist_p     0 0
rscaplae_y   0 0
rshoulder_p  0 0
rshoulder_r  0 -15
rshoulder_y  0 90
relbow_p     0 -15
rwrist_y     0 0
rwrist_r     0 15
rwrist_p     0 0

[mc]
com
waist_base  world_att
left_foot   world_pos
left_foot   world_att
right_foot  world_pos
right_foot  world_att
