[joint]
body                  0.001 0 0 0 0 0 0
left_shoulder_flexion     0 -20
left_shoulder_abduction   0 15
left_elbow_rotation       0 70
left_elbow_flexion        0 60
left_hip_flexion      0.001 0
left_hip_abduction    0.001 0
left_knee_rotation    0.001 0
left_knee_flexion     0.001 0
left_ankle_flexion    0.001 0
left_ankle_abduction  0.001 0
right_shoulder_flexion    0 -20
right_shoulder_abduction  0 15
right_elbow_rotation      0 70
right_elbow_flexion       0 60
right_hip_flexion     0.001 0
right_hip_abduction   0.001 0
right_knee_rotation   0.001 0
right_knee_flexion    0.001 0
right_ankle_flexion   0.001 0
right_ankle_abduction 0.001 0

[mc]
com
body       world_att
left_foot  world_pos
left_foot  world_att
right_foot world_pos
right_foot world_att
